### PR TITLE
First shot at updating Scala.js

### PR DESCRIPTION
**Pull request by nightscape**
Hi Li Haoyi,

I upgraded the Scala.js Version in Workbench to the latest and greatest 0.6.1.
My knowledge of SBT, Scala.js and Workbench itself is rather superficial and I did all changes compile-failure-driven.
It would be great if you could check for semantic correctness :)
I tried this version with your workbench-example-app and I was able to do a
```
sjs println("It works")
```
from the SBT prompt and have it appear in the browser.
Is there something else I can/should check?

Best
  Martin

### CODE REVIEW

**Comment by pasviegas** [comment]
+1

**Comment by giovannicandido** [comment]
+1

**Comment by nightscape** [comment]
Updated to the even newer 0.6.2

**Comment by lihaoyi** [comment]
I have no idea whether this is correct or not, but if running `sjs println` works then it should be ok. Nothing else depends on the Scala.js version.

**Pull request merged**
